version: "3"
services:
  node:
    build:
      context: ./app
    environment:
      - NODE_ENV=production
      - REACT_APP_NAME=profile
    volumes:
      - ./app:/usr/src/app
      #- ./build:/usr/src/build
    ports:
      - "3000:3000"
